name: CI

on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.16.3-otp-26
            otp: 26.2
          - elixir: 1.17.3-otp-27
            otp: 27.3
          - elixir: 1.18.4-otp-28
            otp: 28.0
            lint: true
    env:
      MIX_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore deps and _build cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix test
